baseURL: https://www.freestingo.com/
title: freestingo
theme: nicolo
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
enableGitInfo: true
markup:
  goldmark:
    parser:
      attribute:
        block: true
        title: true
