en:
  contentDir: content/en
  disabled: false
  languageCode: en-US
  languageDirection: ltr
  languageName: en
  title: freestingo
  weight: 1
  permalinks:
    page:
      coding: /coding/:slug/
      music: /music/:slug/
    section:
      coding: /coding/
      music: /music/

it:
  contentDir: content/it
  disabled: false
  languageCode: it-IT
  languageDirection: ltr
  languageName: it
  title: freestingo
  weight: 2
  permalinks:
    page:
      coding: /coding/:slug/
      music: /musica/:slug/
    section:
      coding: /coding/
      music: /musica/
