en:
  contentDir: content/en
  disabled: false
  languageCode: en-US
  languageDirection: ltr
  languageName: en
  title: freestingo
  weight: 1
  permalinks:
    page:
      programming: /programming/:slug/
      music: /music/:slug/
    section:
      programming: /programming/
      music: /music/
    topics: /topics/:slug/

it:
  contentDir: content/it
  disabled: false
  languageCode: it-IT
  languageDirection: ltr
  languageName: it
  title: freestingo
  weight: 2
  permalinks:
    page:
      programming: /programmazione/:slug/
      music: /musica/:slug/
    section:
      programmazione: /programmazione/
      music: /musica/
    topics: /argomenti/:slug/
