en:
  contentDir: content/en
  disabled: false
  languageCode: en-US
  languageDirection: ltr
  languageName: en
  title: freestingo
  weight: 1
  permalinks:
    topics: /topics/:slug/
    artists: /artists/:slug/
    release-years: /release-years/:slug/
    genres: /genres/:slug/
    votes: /votes/:slug/

it:
  contentDir: content/it
  disabled: false
  languageCode: it-IT
  languageDirection: ltr
  languageName: it
  title: freestingo
  weight: 2
  permalinks:
    topics: /argomenti/:slug/
    artists: /artisti/:slug/
    release-years: /anni-di-rilascio/:slug/
    genres: /generi/:slug/
    votes: /voti/:slug/
