social:
  - name: youtube
    url: "https://www.youtube.com/@nicolo6435"
  - name: instagram
    url: "https://www.instagram.com/freestingo"
  - name: linkedin
    url: "https://www.linkedin.com/in/nicolot"
  - name: github
    url: "https://github.com/freestingo"
